### ISSUE TITLE
Use variables in path argument

### ISSUE THREAD

**Issue by just-boris** [sillylogger/jekyll-directory#3]
It would be good if path will might be a variable. Then can be done recursive list of directories:

``` html
{% assign articles_path = 'articles/' %}
{% directory path: 'articles' %}
  <div>
    Category: <b>{{file.name}}</b>
    {% assign folder = articles_path|append:file.name %}
    {% directory path:folder %}
        <div><a href="{{ file.url }}" >{{ file.slug}}</a></div>
    {% enddirectory %}
  </div>
{% enddirectory %}
```

I can submit pull request with needed fixes after you accept the my previous

**Comment by erindru** [comment]
Hey @just-boris do you have the code for this? I tried your fork but it didnt work

**Comment by paulrobertlloyd** [comment]
+1

**Comment by just-boris** [comment]
here it is: https://github.com/allure-framework/allure.qatools.ru/blob/64bc42f54329d2a5d42094549153736e7279c1e6/_plugins/directory_tag.rb

Usage example: https://github.com/allure-framework/allure.qatools.ru/blob/64bc42f54329d2a5d42094549153736e7279c1e6/_layouts/default.html#L29-32

But now we changed our approach at all, so that plugin was removed from actual master

**Comment by paulrobertlloyd** [comment]
Thank-you so much @just-boris for providing this code! I’ve now got this running using a variable – perfect! I did come across one problem though, so for the sake of documenting it, here’s what I changed.

With the variable I supplied, the loop for some reason was generating paths roughly like this:

path/to/location/1.jpg
path/to/location/1.jpg/2.jpg
path/to/location/1.jpg/2.jpg/3.jpg

To fix this, I commented out the following line: https://github.com/paulrobertlloyd/paulrobertlloyd.com/blob/ee32b981c08400a116fded5dc21543995cee3126/source/_plugins/liquid-tags/directory.rb#L72 Seemed to work fine once I had done that :-)

**Comment by KingScooty** [comment]
+1

**Comment by lekarlr** [comment]
@just-boris i try yo use your example but it return " Liquid Exception: can't convert nil into String "

**Comment by just-boris** [comment]
Well, my example is 3 years old. I guess there can be some incompatibility with newer Jekyll versions

**Comment by paulrobertlloyd** [comment]
@lekarlr I was using an adapted version of this plugin until recently, the code for which can be found here: https://github.com/paulrobertlloyd/paulrobertlloyd.com/blob/ee32b981c08400a116fded5dc21543995cee3126/source/_plugins/liquid-tags/directory.rb

Again, it may no longer work, but perhaps worth a shot?

**Comment by lekarlr** [comment]
@paulrobertlloyd tnx, iy try your version too but result is the same  Liquid Exception: can't convert nil into String

**Comment by paulrobertlloyd** [comment]
Whenever I’ve come across this error, it tends to be with the values I’m passing into my template. Perhaps output those separately, outside the scope of this plugin, to see if you get the same error?

**Comment by lekarlr** [comment]
path = @path.render(context).to_s

**Comment by sillylogger** [comment]
Annnnnnd I finally got around to this.  I've updated the plugin to hackily work with Liquid version 4.0 (dependency of the latest Jekyll).  This breaks compatibility with earlier versions, but @just-boris's feature request works.

I need to rewrite the plugin to take advantage of Liquid's [`BlockBody`](https://github.com/Shopify/liquid/blob/master/lib/liquid/block_body.rb)  as the new for loop does: https://github.com/Shopify/liquid/blob/master/lib/liquid/tags/for.rb

**Comment by C4K3** [comment]
It would be nice if this also worked with exclude:

**Comment by sillylogger** [comment]
@C4K3 you're looking for exclude to support variables?  exclude already works: https://github.com/sillylogger/jekyll-directory/blob/master/spec/directory_spec.rb#L64

**Comment by C4K3** [comment]
Apologies, after some testing I figured out the problem was on my end, I had forgotten quotation marks around the string when declaring the variable. Thanks for making a very useful plugin :)
