### ISSUE TITLE
Files with no extension cause an error

### ISSUE THREAD

**Issue by awstlaur** [sillylogger/jekyll-directory#4]
I believe it's at the line 82 `slug = basename.sub(ext, '')` in the plugin file. If the file has no extension (or, in particular, is a sub directory), you get the nasty "Liquid Exception: wrong argument type nil (expected Regexp) in <file>"

I worked around this by replacing that line with

```
if ext
    slug = basename.sub(ext, '')
else
    slug = basename
end
```

**Comment by sillylogger** [comment]
This should be fixed by merging in #2 .. hope that helps.. thanks for kicking me to update this project :-)
